version: "2"

services:
  application:
    image: debian
    volumes:
      - ./:/var/www/app
  workspace:
    image: mrfloat/laravel-env-docker
    restart: always
    volumes_from:
      - application
    tty: true
